# Generated by Django 5.1.4 on 2024-12-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars_reviewsformovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewsForMovie',
        ),
    ]
